# 4.5 读取和存储

In [1]:
import torch
from torch import nn

print(torch.__version__)

2.1.0


## 4.5.1 读写`Tensor`

In [2]:
x = torch.ones(3)
torch.save(x, 'x.pt')

In [3]:
x2 = torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [4]:
y = torch.zeros(4)
torch.save([x, y], 'xy.pt')
xy_list = torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [5]:
torch.save({'x': x, 'y': y}, 'xy_dict.pt')
xy = torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

## 4.5.2 读写模型
### 4.5.2.1 `state_dict`

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP, self).__init__()
        self.hidden = nn.Linear(3, 2)
        self.act = nn.ReLU()
        self.output = nn.Linear(2, 1)

    def forward(self, x):
        a = self.act(self.hidden(x))
        return self.output(a)

net = MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.4356,  0.0006,  0.1568],
                      [-0.4067, -0.0842,  0.5481]])),
             ('hidden.bias', tensor([ 0.2211, -0.4719])),
             ('output.weight', tensor([[ 0.5052, -0.4964]])),
             ('output.bias', tensor([-0.4538]))])

In [7]:
optimizer = torch.optim.SGD(net.parameters(), lr=0.001, momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'maximize': False,
   'foreach': None,
   'differentiable': False,
   'params': [0, 1, 2, 3]}]}

### 4.5.2.2 保存和加载模型

In [8]:
X = torch.randn(2, 3)
Y = net(X)

PATH = "./net.pt"
torch.save(net.state_dict(), PATH)

net2 = MLP()
net2.load_state_dict(torch.load(PATH))
Y2 = net2(X)
Y2 == Y

tensor([[True],
        [True]])