# 4.6 GPU计算

In [8]:
!nvidia-smi
# 对Linux/macOS用户有效

Sun Nov  5 19:45:54 2023       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 545.84                 Driver Version: 545.84       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090      WDDM  | 00000000:01:00.0  On |                  Off |
|  0%   41C    P8              27W / 450W |   1671MiB / 24564MiB |     34%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [9]:
import torch
from torch import nn

print(torch.__version__)

2.1.0


## 4.6.1 计算设备

In [10]:
torch.cuda.is_available() # cuda是否可用

True

In [11]:
torch.cuda.device_count() # gpu数量

1

In [12]:
torch.cuda.current_device() # 当前设备索引, 从0开始

0

In [13]:
torch.cuda.get_device_name(0) # 返回gpu名字

'NVIDIA GeForce RTX 4090'

## 4.6.2 `Tensor`的GPU计算

In [14]:
x = torch.tensor([1, 2, 3])
x

tensor([1, 2, 3])

In [15]:
x = x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [16]:
x.device

device(type='cuda', index=0)

In [17]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

x = torch.tensor([1, 2, 3], device=device)
# or
x = torch.tensor([1, 2, 3]).to(device)
x

tensor([1, 2, 3], device='cuda:0')

In [18]:
y = x**2
y

tensor([1, 4, 9], device='cuda:0')

In [12]:
# z = y + x.cpu()

## 4.6.3 模型的GPU计算

In [19]:
net = nn.Linear(3, 1)
list(net.parameters())[0].device

device(type='cpu')

In [20]:
net.cuda()
list(net.parameters())[0].device

device(type='cuda', index=0)

In [21]:
x = torch.rand(2,3).cuda()
net(x)

tensor([[-0.6773],
        [-0.8913]], device='cuda:0', grad_fn=<AddmmBackward0>)